namdtime = 5000
nelm = 10
ntraj = 10000
shmethod = "FSSH"
detailed_balance = "DependsOnEField"
smearing_method = "LorentzianSmearing"
smearing_sigma = 0.01
smearing_npoints_per_eV = 500
hamil_fname = "../HAMIL-0K-single-electron-efield.h5"
outdir = "result"
iniband = "216"
inisteps = [ 5 ]
